# Generated by Django 4.1.8 on 2023-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chellaboina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='usertype',
            field=models.CharField(choices=[('Normal User', 'Normal User')], default='Normal User', editable=False, max_length=20),
        ),
    ]
